Fix delete video when deleted in Nexx GUI
BurdaMagazinOrg/module-nexx_integration pull request #57
Opened 2018-09-12 15:39 UTC by secmi

2018-09-19 08:15 UTC, dbosen requested changes

2018-09-19 08:15 UTC, dbosen commented on src/Controller/OmniaController.php
> +    return !empty($this->videoData->itemID) ? $this->videoData->itemID : 0;
Why did this change? Does the previous call not work anymore?

2018-09-19 08:15 UTC, dbosen commented on src/Controller/OmniaController.php
> +            '@title' => $media->label(),
Nice simplification :)

2018-09-19 08:17 UTC, dbosen commented on src/Controller/OmniaController.php
> +    if ($this->getTriggerReason() == 'delete' || $this->isVideoDeleted()) {
Both possible delete trigger need to be covered by a test

2018-09-19 14:22 UTC, secmi commented on src/Controller/OmniaController.php
> +    return !empty($this->videoData->itemID) ? $this->videoData->itemID : 0;
Was working only for update/create trigger, because itemID is there on two places. This location is valid for all triggers.

2018-09-19 18:24 UTC, secmi commented on src/Controller/OmniaController.php
> +    if ($this->getTriggerReason() == 'delete' || $this->isVideoDeleted()) {
Done

2018-09-20 07:38 UTC, dbosen approved these changes

2018-09-20 07:38 UTC, merged